version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: PROPl4n3t
      MYSQL_DATABASE: todo
    ports:
      - "3308:3306"
  rest-api:
    build: .
    depends_on:
      - "mysql"
    ports:
      - "8080:8080"
